version: '2.4'
services:
    novaas:
        build: .
        image: "registry.gitlab.com/novaas/catalog/nova-school-of-science-and-technology/novaas-openid-phoenix-i40:latest"
        environment:
            - "PORT_FORWARDING=${PORT_FORWARDING}" 
            - "HOST=${HOST}"
            - "BROKER_SERVICE_HOST=${BROKER_SERVICE_HOST}"
            - "BROKER_SERVICE_PORT=${BROKER_SERVICE_PORT}"
            - "OPEN_ID=${OPEN_ID}"
        ports:
            - "${PORT_FORWARDING}:1880"