version: '2.4'
services:
    novaas:
        build: .
        image: "novaas_festo_dpdm/openid/dockerbase:1.0.0"
        environment:
            - "PORT_FORWARDING=${PORT_FORWARDING}" 
            - "HOST=${HOST}"
        ports:
            - "${PORT_FORWARDING}:1880"